config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :users
  root 'home#top'

  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { in: 2..20}, presence: true
  validates :introduction,    length: { maximum: 50 }

  attachment :profile_image


  has_many :books, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
   	   user_path(current_user)
   end

   def after_sign_up_path_for(resource)
   	   root_path
   end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,  keys: [:email])
    # devise_parameter_sanitizer.permit(:sign_in,  keys: [:password])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!


  def index
  	  @books = Book.all
  	  @book = Book.new
      @user = current_user
  end

  def show
  	  @book = Book.find(params[:id])
      @book_new = Book.new
  end

  def new
  	  @book = Book.new
  end

  def top
  end

  def create
  	   @book = Book.new(book_params)
       @book.user_id = current_user.id
  	if @book.save
  	   redirect_to book_path(@book.id)
  	   flash[:notice] = "Book was successfully created."
  	else
  	   @books = Book.all
       @user = current_user
  	   render :index
  	end

  end

  def edit
  	  @book = Book.find(params[:id])
      if @book.user.id == current_user.id
        @user = current_user
      else
        redirect_to books_path
      end
  end

  def update
  	  @book = Book.find(params[:id])
  	  if @book.update(book_params)
  	  	redirect_to book_path(@book.id)
  	  	flash[:notice] = "Book was successfully updated."
  	  else
  	  	render :edit
  	  end
  end

  def destroy
  	  book = Book.find(params[:id])
  	  book.destroy
  	  redirect_to books_path
  	  flash[:notice] = "Book was successfully destroyed."
  end

  private
  def book_params
  	params.require( :book).permit( :title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	flash[:sign_out] = "Signed out successfully"
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!
  def index
      @user= current_user
  	  @users =  User.all
      @book = Book.new
  end
  def show
  	  @user = User.find(params[:id])
      @book = Book.new
      @books = Book.all
  end

  def create
    user = User.new(user_params)
    user.save
  end

  def top
     @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

 def update
  @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "successfully"
     redirect_to user_path(@user.id)
   else
     render :edit
  end
 end

 private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new_book.html.erb
<h2>New book</h2>
<%= form_for(book) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "col-xs-12 book_title" %>
  </div>

  <div class="field row">
    <label for="book_body">Body</label>
    <%= f.text_area :body, class: "col-xs-12 book_body" %>
  </div>

  <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>

<% end %>

app/views/books/edit.html.erb
<div class="container">

	<p id="notice"></p>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<!-- <div class='col-md-3 col-md-offset-3'>
			</div> -->
			<%= form_for(@book) do |f| %>
				<%= render 'layouts/error_messages', model: f.object %>
				<div class="field row">
					<label for="book_title">Title</label>
					<%= f.text_field :title ,class: "col-xs-12 book_title" %>
				</div>

				<div class="field row">
					<label for="book_opinion">Opinion</label>
					<%= f.text_area :body ,class: "col-xs-12 book_body"%>
				</div>

				<div class="actions row">
					<%= f.submit 'Update Book',class: "btn btn-primary col-xs-12" %>
				</div>
			<% end %>
			<%= link_to 'Show', book_path(@book.id) %> |
			<%= link_to 'Back', books_path %>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">

    <p id="notice"></p>

    <%= flash[:notice] %>
    <div class="row">
      <div class="col-xs-3">
        <%= render 'users/user_info', user: @user %>

        <%= render 'new_book', book: @book %>
      </div>

      <div class="col-xs-9">
        <h2>Books</h2>

        <table class="table table-hover table-inverse">
      <thead>
        <tr> 
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to (book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: 'no_image.jpg',size:'35x35' %>
              <% end %>
           </td>
            <td>
              <%= link_to (book) do %>
              <%= book.title %>
              <% end %>
              </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>

      </tbody>
    </table>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
      <div class="container">

        <p id="notice"></p>

<%= flash[:notice] %>
  <div class="row">
  <div class="col-xs-3">
  <%= render 'users/user_info', user: @book.user %>
    <%= render 'new_book', book: @book_new %>
  </div>


  <div class="col-xs-9">
		<h2>Book detail</h2>
		<table class="table">
		  <tbody><tr>
        <td>
          <%= link_to(@book.user) do %>
          <%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: 'no_image.jpg',size:'35x35' %><br>
          <%= @book.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to(@book) do %>
          <%= @book.title %>
          <% end %>
        </td>
        <td><%= @book.body %></td>
        <% if @book.user.id == current_user.id %>
          <td><%= link_to 'Edit', edit_book_path(@book.id),class: "btn-sm btn-success" %></td>
          <td><%= link_to 'Destroy', book_path(@book.id), method: :delete ,class: "btn-sm btn-danger",data: { confirm: '削除しますか？' }%></td>
        <% end %>

      </tr>
    </tbody></table>

  </div>
</div>
      </div>

app/views/home/about.html.erb
      <div class="container">

        <p id="notice"></p>


      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">

    <p id="notice"></p>

    <%if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <div class="top-message col-md-offset-3 col-md-6">
      <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
      <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>

      <div class="btn-wrapper">
      <!-- <div class="row"> -->
      <!--          <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      -->         
            <%= link_to 'Log in', new_user_session_path,class: "btn btn-info col-xs-12 col-xs-offset-1 sign_in" %>
          
      <!-- </div> -->
      <!-- <div class="row"> -->

            <%= link_to 'Sign up', new_user_registration_path,class: "btn btn-success col-xs-12 col-xs-offset-1 sign_up" %>
                <!-- </div> -->
      </div>

    </div>
  </div>


</div>

app/views/layouts/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class="error_explanation">
  	<h2><%= pluralize(@book.errors.count,"error") %></h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h4 class="nav-title">
            Bookers
          </h4>

        </div>

        <div class="collapse navbar-collapse" id="navbarEexample">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' Home', user_path(current_user) ,class: "glyphicon glyphicon-home home"%></li>
              <li><%= link_to ' Users', users_path ,class: "glyphicon glyphicon-user users"%></li>
              <li><%= link_to ' Books', books_path ,class: "glyphicon glyphicon-book books"%></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: "glyphicon glyphicon-log-out logout"%></li>
            <% else %>
              <li><%= link_to ' Home', root_path ,class: "glyphicon glyphicon-home home" %></li>
              <li><%= link_to ' About', "/home/about" ,class: "glyphicon glyphicon-link link" %></li>
              <li><%= link_to ' sign up',new_user_registration_path,class: "glyphicon glyphicon-edit edit" %></li>
              <li><%= link_to ' login', "/users/sign_in" ,class: "glyphicon glyphicon-log-in login" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>


      <%= yield %>

      <footer>
        <div class="container">
          <div class="row">
            <div class="col-xs-3 col-xs-offset-9">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>
</body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: 'no_image.jpg' %>
      <table class= "table">
      <tbody><tr></tr>
      <tr>
        <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
        <th><%=user.introduction%></th>
      </tr>
      </tbody>
     </table>

<div class="row">
  <% if user.id == current_user.id %>
    <%= link_to "", edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench user_#{user.id} " %>
  <% else %>
    <%= link_to "", user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench user_#{user.id} " %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">

  <p id="notice"></p>
  	<h2>User info</h2>
<% if @user.errors.any? %>
  <div class="error_explanation">
    <h2><%= pluralize(@user.errors.count,"error") %></h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= form_for(@user) do |f| %>

    <div class="form-group has-icon">
      <label for="user_name">Name</label>
      <%= f.text_field :name, autofocus: true, id:"inputEmail", placeholder:"名前"%>
      <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

    <div class="form-group has-icon">
       <div class="user-edit-image">
       	<%= f.attachment_field :profile_image %>
       </div>
       <label class="control-label sr-only" for="inputEmail">ProfileImage</label>


  <div class="field">
    <label for="user_introduction">Introduction</label>
    <!-- <textarea class="introduction" name="user[introduction]" id="user_introduction"></textarea> -->
      <%= f.text_area :introduction %>
  </div>

  <div class="actions">
    <%= f.submit 'Update User' %>
  </div>

  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

      <div class="container">

        <p id="notice"></p>

      	<div class="row">

  <div class="col-xs-3">

    <%= render 'users/user_info', user: @user %>

    <%= render 'books/new_book', book: @book %>
  </div>

  

  <div class="col-xs-9">
    <h2>Users</h2>

    <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 35, 35, fallback: 'no_image.jpg',size:'35x35' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>

</div>
      </div>

app/views/users/show.html.erb
<div class="container">

  <p id="notice"></p>
  <%= flash[:notice] %>
  <div class="row">

    <div class="col-xs-3">
      <%= render 'users/user_info', user: @user %>
    	<%= render 'books/new_book', book: @book %>
    </div>

    <div class="col-xs-9">
      <h2>Books</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr> 
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
         <% @user.books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 35, 35, fallback: 'no_image.jpg',size:'35x35' %>
              <% end %>
            </td>
            <td>
              <%= link_to (book) do %>
              <%= book.title %>
              <% end %>
              </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class="container">

  <p id="notice"></p>


      	<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>

  </div>
</div>


      </div>